id: P4FFB3922
initial_creation_type: input
source_metadata:
  Title: Abhisamayalankarantah patinam
  Editor: Tripathi, Ram Shankar
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '1977'
  Abhisamayālaṅkārāntaḥ pātināṃ padārthānāṃ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:45:43.473659'
last_modified_at: '2022-03-08T16:45:43.473667'
